# SPDX-License-Identifier: MIT
"""Measure each corpus with each constricter version, and record the results in docs/RUNS.md.

    local/.venv/bin/python tests/corpus_table.py                          # 0.2.2, 0.2.3 and dev: print
    local/.venv/bin/python tests/corpus_table.py --versions 0.2.3,dev     # only these versions
    local/.venv/bin/python tests/corpus_table.py --versions dev --write   # record dev in docs/RUNS.md

The corpora are this Python's standard library and the pinned `corpus` dependency group's
packages (`uv sync --group dev --group corpus`). A version is a release from PyPI, installed with
`uv` into `local/corpus-table/venvs/`, or `dev`, this checkout (recorded as `<__version__>+dev`).
Each runs isolated (`python -I`, from `local/corpus-table/`), so neither this checkout nor its
`pyproject.toml` leaks into a release's run.

For each corpus and version: a check at every level (with `--all-scopes`), counted per code at
`suffocate` and as errors and warnings at each level, by that version's own rules and defaults;
then `--fix` and `--fix --unsafe-fixes` on copies, counting what each fixed, what no longer
compiles, and what a second pass would still fix. `--write` adds a section per version to
docs/RUNS.md, or replaces a release's section if it's there; `dev` is recorded under this
checkout's version, so record it right after bumping the version for a release (`--replace` to
overwrite a section already there). Timings go to standard error, not
the tables, so rerunning it on an unchanged tree changes nothing.
"""

import importlib
import json
import os
import re
import shutil
import subprocess  # runs each version under test
import sys
import sysconfig
import time
import warnings
from collections import Counter
from collections.abc import Sequence
from importlib import metadata
from pathlib import Path
from typing import Final, NamedTuple, TypeAlias, cast

from constricter import Level, __version__
from constricter.cli import paths

_Json: TypeAlias = "str | int | list[_Json] | dict[str, _Json] | None"
_ROOT: Final = Path(__file__).resolve().parents[1]
RUNS: Final = _ROOT / "docs" / "RUNS.md"
WORK: Final = _ROOT / "local" / "corpus-table"
DEV: Final = "dev"
VERSIONS: Final = ("0.2.2", "0.2.3", DEV)
# The `corpus` dependency group's packages, by import name (their distribution names match).
PACKAGES: Final = ("requests", "flask", "django", "sqlalchemy")
_EVERYWHERE: Final = ("--all-scopes", "--jobs=0")
_FIXED: Final = re.compile(r"fixed (\d+)")
_SECTION: Final = "## constricter "
_WINDOWS: Final = "nt"
_ERROR: Final = "error"
_VERSIONS_FLAG: Final = "--versions"
_WRITE_FLAG: Final = "--write"
_REPLACE_FLAG: Final = "--replace"
_RUNS_HEADER: Final = """# Corpus runs

What each constricter version found and fixed on the corpus: this Python's standard library and
the pinned `corpus` packages, at every level with `all-scopes`. Regenerated by
`tests/corpus_table.py`; a section per version, added when the version goes up (see
[CONTRIBUTING](CONTRIBUTING.md)).
"""


class Corpus(NamedTuple):
    """One codebase to measure: its name, version, and the directory checked."""

    name: str
    version: str
    root: Path


class Measured(NamedTuple):
    """What one constricter version gave on one corpus."""

    corpus: Corpus
    version: str  # constricter's, as recorded (`dev` as `<__version__>+dev`)
    files: int
    codes: Counter[str]  # at `suffocate`
    levels: dict[Level, tuple[int, int]]  # each level's errors and warnings
    fixed: int | None  # `None`: the version's `--fix` crashed
    guessed: int | None  # fixed only with `--unsafe-fixes`, beyond `fixed`
    broken: int  # files that compiled before `--fix --unsafe-fixes` and don't after
    left: int  # what a second `--fix --unsafe-fixes` pass would still fix


def corpora() -> list[Corpus]:
    """Find the standard library and each installed `corpus` package.

    Returns:
      Them; a package that isn't installed is left out, with a note on standard error.

    """
    found: list[Corpus] = [
        Corpus("standard library", sysconfig.get_python_version(), Path(sysconfig.get_paths()["stdlib"])),
    ]
    name: str
    for name in PACKAGES:
        try:
            module_file: str | None = importlib.import_module(name).__file__
        except ImportError:
            _ = sys.stderr.write(f"{name} isn't installed: run `uv sync --group dev --group corpus`\n")
            continue
        found.append(Corpus(name, metadata.version(name), Path(cast("str", module_file)).parent))
    return found


def label(version: str) -> str:
    """Name a version as it's recorded: a release as itself, `dev` as `<__version__>+dev`.

    Returns:
      The label.

    """
    return f"{__version__}+{DEV}" if version == DEV else version


def interpreter(version: str) -> str:
    """Find a Python that runs `version` of constricter, installing a released one the first time.

    Returns:
      Its path: this Python for `dev`, else the one in `local/corpus-table/venvs/<version>`.

    """
    if version == DEV:
        return sys.executable
    venv: Path = WORK / "venvs" / version
    python: Path = venv / ("Scripts/python.exe" if os.name == _WINDOWS else "bin/python")
    if not python.exists():
        uv: str = os.environ.get("UV") or shutil.which("uv") or "uv"
        _ = subprocess.run([uv, "venv", "-q", "--python", sys.executable, str(venv)], check=True)
        _ = subprocess.run(
            [uv, "pip", "install", "-q", "--python", str(python), f"python-constricter=={version}"],
            check=True,
        )
    return str(python)


def _run(python: str, args: Sequence[str]) -> str:
    """Run a version's command, isolated: `-I`, from `WORK`, so no checkout or config leaks in.

    Returns:
      Its standard output.

    """
    WORK.mkdir(parents=True, exist_ok=True)
    done: subprocess.CompletedProcess[str] = subprocess.run(
        [python, "-I", "-W", "ignore", "-m", "constricter", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
        cwd=WORK,
    )
    return done.stdout


def _compiles(path: Path) -> bool:
    source: bytes = path.read_bytes()
    with warnings.catch_warnings(action="ignore"):  # the standard library's tests warn
        try:
            _ = compile(source, str(path), "exec", dont_inherit=True)
        except (SyntaxError, ValueError):
            return False
    return True


def _fixed_count(output: str) -> int | None:
    """Read how many offences a `--fix` run fixed, from its summary line.

    Returns:
      The count, or `None` if it printed none: it crashed (0.2.2's does on a file that isn't UTF-8).

    """
    found: re.Match[str] | None = _FIXED.search(output)
    return int(found.group(1)) if found else None


def _copy(corpus: Corpus, version: str) -> tuple[Path, list[Path]]:
    """Copy a corpus's Python files under `WORK`, fresh, for one version to fix.

    Returns:
      The copy's root, and each copied file that compiles.

    """
    root: Path = WORK / version / corpus.name.replace(" ", "-")
    shutil.rmtree(root, ignore_errors=True)
    valid: list[Path] = []
    source: Path
    for source in paths.python_files([corpus.root]):
        copy: Path = root / source.relative_to(corpus.root)
        copy.parent.mkdir(parents=True, exist_ok=True)
        _ = shutil.copyfile(source, copy)
        if _compiles(copy):
            valid.append(copy)
    return root, valid


def _checked(python: str, root: Path) -> tuple[Counter[str], dict[Level, tuple[int, int]]]:
    """Check `root` at every level.

    Returns:
      The offences per code at `suffocate` (which reports every code), and each level's errors and
      warnings.

    """
    codes: Counter[str] = Counter()
    levels: dict[Level, tuple[int, int]] = {}
    level: Level
    for level in Level:
        output: str = _run(
            python,
            ["--format=json", f"--level={level.name.lower()}", *_EVERYWHERE, str(root)],
        )
        results: list[dict[str, _Json]] = cast("list[dict[str, _Json]]", json.loads(output or "[]"))
        errors: int = sum(r["severity"] == _ERROR for r in results)
        levels[level] = (errors, len(results) - errors)
        codes = Counter(str(r["code"]) for r in results)  # the last level's is `suffocate`'s
    return codes, levels


def _fixes(python: str, corpus: Corpus, version: str) -> tuple[int | None, int | None, int, int]:
    """Fix copies of `corpus`: certain fixes only, then guesses too.

    Returns:
      How many certain fixes, how many more guesses, files the guesses broke, and what a second
      pass would still fix.

    """
    fixing: list[str] = ["--level=suffocate", *_EVERYWHERE]
    root: Path
    valid: list[Path]
    root, _ = _copy(corpus, version)
    fixed: int | None = _fixed_count(_run(python, ["--fix", *fixing, str(root)]))
    root, valid = _copy(corpus, version)
    both: int | None = _fixed_count(_run(python, ["--fix", "--unsafe-fixes", *fixing, str(root)]))
    broken: int = sum(not _compiles(path) for path in valid)
    left: int = _run(python, ["--diff", "--unsafe-fixes", *fixing, str(root)]).count("\n+")
    return fixed, None if fixed is None or both is None else both - fixed, broken, left


def measure(corpus: Corpus, version: str) -> Measured:
    """Check and fix one corpus with one version.

    Returns:
      What it gave.

    """
    start: float = time.perf_counter()
    python: str = interpreter(version)
    files: int = sum(1 for _ in paths.python_files([corpus.root]))
    codes: Counter[str]
    levels: dict[Level, tuple[int, int]]
    codes, levels = _checked(python, corpus.root)
    fixes: tuple[int | None, int | None, int, int] = _fixes(python, corpus, version)
    seconds: float = time.perf_counter() - start
    _ = sys.stderr.write(f"{version} on {corpus.name}: {files} files in {seconds:.1f}s\n")
    return Measured(corpus, label(version), files, codes, levels, *fixes)


def _table(rows: Sequence[Sequence[object]], right: int) -> list[str]:
    """Lay a table out as Prettier does, so CI's `prettier --check` passes on what this writes.

    `rows[0]` is the header; the first `right` columns align left, the rest (numbers) right.

    Returns:
      Its lines: the header, the alignment row, then each row, every cell padded to its column.

    """
    cells: list[list[str]] = [[str(cell) for cell in row] for row in rows]
    widths: list[int] = [max(3, *(len(row[i]) for row in cells)) for i in range(len(cells[0]))]
    separator: list[str] = ["-" * w if i < right else "-" * (w - 1) + ":" for i, w in enumerate(widths)]

    def line(row: Sequence[str]) -> str:
        padded: list[str] = [
            cell.ljust(widths[i]) if i < right else cell.rjust(widths[i]) for i, cell in enumerate(row)
        ]
        return "| " + " | ".join(padded) + " |"

    return [line(cells[0]), "| " + " | ".join(separator) + " |", *(line(row) for row in cells[1:])]


def _number(count: int | None) -> str:
    return "crashed" if count is None else f"{count:,}"


def tables(measured: Sequence[Measured]) -> str:
    """Write the two tables as Markdown, a row per corpus and version.

    Returns:
      The offences per code at `suffocate` (every code a version reports), then each level's errors
      and warnings and what `--fix` did, with a line naming the Python they came from.

    """
    codes: list[str] = sorted({code for m in measured for code in m.codes})
    first: list[str] = _table(
        [
            ["Corpus", "Version", "constricter", "Files", *(f"`{code}`" for code in codes)],
            *(
                [
                    m.corpus.name,
                    m.corpus.version,
                    m.version,
                    _number(m.files),
                    *(_number(m.codes[c]) for c in codes),
                ]
                for m in measured
            ),
        ],
        right=3,
    )
    levels: list[Level] = list(Level)
    second: list[str] = _table(
        [
            [
                "Corpus",
                "constricter",
                *(f"`{level.name.lower()}`" for level in levels),
                "Fixed",
                "Guessed",
                "Broken",
                "Left",
            ],
            *(
                [
                    m.corpus.name,
                    m.version,
                    *(f"{_number(m.levels[level][0])} / {_number(m.levels[level][1])}" for level in levels),
                    _number(m.fixed),
                    _number(m.guessed),
                    m.broken,
                    m.left,
                ]
                for m in measured
            ),
        ],
        right=2,
    )
    python: str = sys.version.split()[0]
    return "\n".join(
        [
            f"Offences per code at `suffocate`, with `all-scopes` (Python {python}):",
            "",
            *first,
            "",
            "Errors / warnings at each level, by the version's own rules and defaults; what `--fix`",
            "fixed, what `--unsafe-fixes` guessed on top, files a fix broke, and what a second pass would",
            "still fix:",
            "",
            *second,
        ],
    )


def record(measured: Sequence[Measured], runs: Path = RUNS, *, replace: bool = False) -> None:
    """Write a section per version into `runs`, replacing a release's section if it's there.

    Sections stay in the order they were first added: a new version's is appended. `dev` is
    recorded under this checkout's own version (so run it right after bumping the version for a
    release), and never over a section already there unless `replace`: that version was
    released, and its section is the release's.

    Raises:
      ValueError: `dev` would overwrite a recorded version.

    """
    text: str = runs.read_text(encoding="utf-8") if runs.exists() else _RUNS_HEADER
    head: str
    rest: list[str]
    head, *rest = text.split(f"\n{_SECTION}")
    sections: dict[str, str] = {}
    part: str
    for part in rest:
        name: str = part.split("\n", 1)[0]
        sections[name] = part
    version: str
    for version in dict.fromkeys(m.version for m in measured):
        release: str = version.removesuffix(f"+{DEV}")
        if release != version and release in sections and not replace:
            message: str = f"{runs} already has {release}: bump the version first, or pass --replace"
            raise ValueError(message)
        rows: list[Measured] = [m._replace(version=release) for m in measured if m.version == version]
        sections[release] = f"{release}\n\n{tables(rows)}\n"
    body: str = "".join(f"\n{_SECTION}{part.rstrip()}\n" for part in sections.values())
    _ = runs.write_text(f"{head.rstrip()}\n{body}", encoding="utf-8")


def main(argv: Sequence[str]) -> int:
    """Measure every corpus with every version, print the tables and, with `--write`, record them.

    Returns:
      0.

    """
    versions: list[str] = list(VERSIONS)
    if _VERSIONS_FLAG in argv:
        versions = argv[argv.index(_VERSIONS_FLAG) + 1].split(",")
    measured: list[Measured] = [measure(corpus, version) for version in versions for corpus in corpora()]
    _ = sys.stdout.write(f"{tables(measured)}\n")
    if _WRITE_FLAG in argv:
        record(measured, replace=_REPLACE_FLAG in argv)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
