# SPDX-License-Identifier: MIT
"""Measure each corpus with each constricter version, and record the results in docs/RUNS.md.

    local/.venv/bin/python tests/corpus/corpus_table.py                          # 0.2.2, 0.2.3 and dev: print
    local/.venv/bin/python tests/corpus/corpus_table.py --versions 0.2.3,dev     # only these versions
    local/.venv/bin/python tests/corpus/corpus_table.py --versions dev --write   # record dev in docs/RUNS.md
    local/.venv/bin/python tests/corpus/corpus_table.py --versions dev --label 0.2.4-rc.1 --write  # as that

The corpora are this Python's standard library, the pinned `corpus` dependency group's packages
(`uv sync --group dev --group corpus`), and the pure Python 2 sources tests/corpus/corpus_sources.py
fetches. A version is a release from PyPI, installed with
`uv` into `local/corpus-table/venvs/`, or `dev`, this checkout (recorded as `<__version__>+dev`, or
`<label>+dev` with `--label`: a pseudo-version, like a release candidate, without bumping it).
Each runs isolated (`python -I`, from `local/corpus-table/`), so neither this checkout nor its
`pyproject.toml` leaks into a release's run.

For each corpus and version: a check at every level (with `--all-scopes`), counted per code at
`suffocate` and as errors and warnings at each level, by that version's own rules and defaults;
then `--fix` and `--fix --unsafe-fixes` on copies, counting what each fixed, what no longer
compiles, and what a second pass would still fix. Each version's rows end in a total: each code's
share of the offences, and what was fixed and guessed as a share of them. `--write` adds a section
per version to docs/RUNS.md, or replaces a release's section if it's there; `dev` is recorded under this
checkout's version, so record it right after bumping the version for a release (`--replace` to
overwrite a section already there). Timings go to standard error, not
the tables, so rerunning it on an unchanged tree changes nothing.
"""

import importlib
import json
import os
import re
import shutil
import subprocess  # runs each version under test
import sys
import sysconfig
import textwrap
import time
import warnings
from collections import Counter
from collections.abc import Iterable, Sequence
from importlib import metadata
from pathlib import Path
from typing import Final, NamedTuple, TypeAlias, cast

from constricter import Level, __version__
from constricter.cli import paths

_Json: TypeAlias = "str | int | list[_Json] | dict[str, _Json] | None"
_ROOT: Final = Path(__file__).resolve().parents[2]
RUNS: Final = _ROOT / "docs" / "RUNS.md"
WORK: Final = _ROOT / "local" / "corpus-table"
DEV: Final = "dev"
VERSIONS: Final = ("0.2.2", "0.2.3", DEV)
# The `corpus` dependency group's packages, by import name (their distribution names match).
PACKAGES: Final = (
    "django",
    "sqlalchemy",
    "pydantic",
    "rich",
    "sentry_sdk",
    "pandas",
)
_SOURCES: Final = Path(__file__).with_name("corpus_sources.py")
_EVERYWHERE: Final = ("--all-scopes", "--jobs=0")
_FIXED: Final = re.compile(r"fixed (\d+)")
_SECTION: Final = "## constricter "
_WINDOWS: Final = "nt"
_ERROR: Final = "error"
_VERSIONS_FLAG: Final = "--versions"
_WRITE_FLAG: Final = "--write"
_REPLACE_FLAG: Final = "--replace"
_LABEL_FLAG: Final = "--label"
_PROSE_WIDTH: Final = 100  # .prettierrc.yaml's printWidth
_GROWTH_NOTE: Final = (
    "How much fixing grew the corpus's Python files: bytes and lines added (and their share), and "
    "bytes per fix, by `--fix` and then by `--fix --unsafe-fixes` (certain fixes and guesses) on a "
    "fresh copy:"
)
_GROWTH_HEADER: Final = [
    "Corpus",
    "constricter",
    "Bytes",
    "Lines",
    "`--fix`: bytes",
    "lines",
    "per fix",
    "`--unsafe-fixes`: bytes",
    "lines",
    "per fix",
]
_LEVELS_NOTE: Final = (
    "Errors / warnings at each level, by the version's own rules and defaults; what `--fix` fixed and "
    "what `--unsafe-fixes` guessed on top (each also as a share of the offences at `suffocate`), files "
    "a fix broke, and what a second pass would still fix:"
)
_RUNS_HEADER: Final = """# Corpus runs

What each constricter version found and fixed on the corpus: this Python's standard library and
the pinned `corpus` packages, at every level with `all-scopes`. Regenerated by
`tests/corpus/corpus_table.py`; a section per version, added when the version goes up (see
[CONTRIBUTING](CONTRIBUTING.md)).
"""


class Corpus(NamedTuple):
    """One codebase to measure: its name, version, and the directory checked."""

    name: str
    version: str
    root: Path


class Measured(NamedTuple):
    """What one constricter version gave on one corpus."""

    corpus: Corpus
    version: str  # constricter's, as recorded (`dev` as `<__version__>+dev`)
    files: int
    codes: Counter[str]  # at `suffocate`
    levels: dict[Level, tuple[int, int]]  # each level's errors and warnings
    fixed: int | None  # `None`: the version's `--fix` crashed
    guessed: int | None  # fixed only with `--unsafe-fixes`, beyond `fixed`
    broken: int  # files that compiled before `--fix --unsafe-fixes` and don't after
    left: int  # what a second `--fix --unsafe-fixes` pass would still fix
    size: "Size"  # the corpus's Python files, before any fix
    fixed_size: "Size | None"  # after `--fix` (`None`: it crashed)
    unsafe_size: "Size | None"  # after `--fix --unsafe-fixes`


class Size(NamedTuple):
    """How big a tree's Python files are, together."""

    size: int  # bytes
    lines: int


def _size(root: Path) -> Size:
    """Measure every Python file under `root`.

    Returns:
      Their bytes and lines, added up.

    """
    data: list[bytes] = [path.read_bytes() for path in paths.python_files([root])]
    return Size(sum(len(chunk) for chunk in data), sum(chunk.count(b"\n") for chunk in data))


def corpora() -> list[Corpus]:
    """Find the standard library, each installed `corpus` package, and each fetched source.

    Returns:
      Them; a package that isn't installed is left out, with a note on standard error.

    """
    found: list[Corpus] = [
        Corpus("standard library", sysconfig.get_python_version(), Path(sysconfig.get_paths()["stdlib"])),
    ]
    name: str
    for name in PACKAGES:
        try:
            module_file: str | None = importlib.import_module(name).__file__
        except ImportError:
            _ = sys.stderr.write(f"{name} isn't installed: run `uv sync --group dev --group corpus`\n")
            continue
        found.append(Corpus(name, metadata.version(name), Path(cast("str", module_file)).parent))
    described: str = subprocess.run(
        [sys.executable, str(_SOURCES), "--describe"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    line: str
    for line in described.splitlines():
        source: str
        version: str
        root: str
        source, version, root = line.split("\t")
        found.append(Corpus(source, version, Path(root)))
    return found


def label(version: str, name: str = __version__) -> str:
    """Name a version as it's recorded: a release as itself, `dev` as `<name>+dev`.

    Returns:
      The label; `name` is this checkout's version unless `--label` gives another.

    """
    return f"{name}+{DEV}" if version == DEV else version


def interpreter(version: str) -> str:
    """Find a Python that runs `version` of constricter, installing a released one the first time.

    Returns:
      Its path: this Python for `dev`, else the one in `local/corpus-table/venvs/<version>`.

    """
    if version == DEV:
        return sys.executable
    venv: Path = WORK / "venvs" / version
    python: Path = venv / ("Scripts/python.exe" if os.name == _WINDOWS else "bin/python")
    if not python.exists():
        uv: str = os.environ.get("UV") or shutil.which("uv") or "uv"
        _ = subprocess.run([uv, "venv", "-q", "--python", sys.executable, str(venv)], check=True)
        _ = subprocess.run(
            [uv, "pip", "install", "-q", "--python", str(python), f"python-constricter=={version}"],
            check=True,
        )
    return str(python)


def _run(python: str, args: Sequence[str]) -> str:
    """Run a version's command, isolated: `-I`, from `WORK`, so no checkout or config leaks in.

    Returns:
      Its standard output.

    """
    WORK.mkdir(parents=True, exist_ok=True)
    done: subprocess.CompletedProcess[str] = subprocess.run(
        [python, "-I", "-W", "ignore", "-m", "constricter", *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
        cwd=WORK,
    )
    return done.stdout


def _compiles(path: Path) -> bool:
    source: bytes = path.read_bytes()
    with warnings.catch_warnings(action="ignore"):  # the standard library's tests warn
        try:
            _ = compile(source, str(path), "exec", dont_inherit=True)
        except (SyntaxError, ValueError):
            return False
    return True


def _fixed_count(output: str) -> int | None:
    """Read how many offences a `--fix` run fixed, from its summary line.

    Returns:
      The count, or `None` if it printed none: it crashed (0.2.2's does on a file that isn't UTF-8).

    """
    found: re.Match[str] | None = _FIXED.search(output)
    return int(found.group(1)) if found else None


def _copy(corpus: Corpus, version: str) -> tuple[Path, list[Path]]:
    """Copy a corpus's Python files under `WORK`, fresh, for one version to fix.

    Returns:
      The copy's root, and each copied file that compiles.

    """
    root: Path = WORK / version / corpus.name.replace(" ", "-")
    shutil.rmtree(root, ignore_errors=True)
    valid: list[Path] = []
    source: Path
    for source in paths.python_files([corpus.root]):
        copy: Path = root / source.relative_to(corpus.root)
        copy.parent.mkdir(parents=True, exist_ok=True)
        _ = shutil.copyfile(source, copy)
        if _compiles(copy):
            valid.append(copy)
    return root, valid


def _checked(python: str, root: Path) -> tuple[Counter[str], dict[Level, tuple[int, int]]]:
    """Check `root` at every level.

    Returns:
      The offences per code at `suffocate` (which reports every code), and each level's errors and
      warnings.

    """
    codes: Counter[str] = Counter()
    levels: dict[Level, tuple[int, int]] = {}
    level: Level
    for level in Level:
        output: str = _run(
            python,
            ["--format=json", f"--level={level.name.lower()}", *_EVERYWHERE, str(root)],
        )
        results: list[dict[str, _Json]] = cast("list[dict[str, _Json]]", json.loads(output or "[]"))
        errors: int = sum(r["severity"] == _ERROR for r in results)
        levels[level] = (errors, len(results) - errors)
        codes = Counter(str(r["code"]) for r in results)  # the last level's is `suffocate`'s
    return codes, levels


class _Fixing(NamedTuple):
    """What fixing copies of a corpus did: `Measured`'s last fields, in its order."""

    fixed: int | None
    guessed: int | None
    broken: int
    left: int
    size: Size
    fixed_size: Size | None
    unsafe_size: Size | None


def _fixes(python: str, corpus: Corpus, version: str) -> _Fixing:
    """Fix copies of `corpus`: certain fixes only, then guesses too, measuring each copy.

    Returns:
      How many certain fixes, how many more guesses, files the guesses broke, what a second pass
      would still fix, and how big the files were before and after each.

    """
    fixing: list[str] = ["--level=suffocate", *_EVERYWHERE]
    root: Path
    valid: list[Path]
    root, _ = _copy(corpus, version)
    size: Size = _size(root)
    fixed: int | None = _fixed_count(_run(python, ["--fix", *fixing, str(root)]))
    fixed_size: Size = _size(root)
    root, valid = _copy(corpus, version)
    both: int | None = _fixed_count(_run(python, ["--fix", "--unsafe-fixes", *fixing, str(root)]))
    unsafe_size: Size = _size(root)
    broken: int = sum(not _compiles(path) for path in valid)
    left: int = _run(python, ["--diff", "--unsafe-fixes", *fixing, str(root)]).count("\n+")
    return _Fixing(
        fixed,
        None if fixed is None or both is None else both - fixed,
        broken,
        left,
        size,
        None if fixed is None else fixed_size,
        None if both is None else unsafe_size,
    )


def measure(corpus: Corpus, version: str, name: str = __version__) -> Measured:
    """Check and fix one corpus with one version (`dev` recorded under `name`).

    Returns:
      What it gave.

    """
    start: float = time.perf_counter()
    python: str = interpreter(version)
    files: int = sum(1 for _ in paths.python_files([corpus.root]))
    codes: Counter[str]
    levels: dict[Level, tuple[int, int]]
    codes, levels = _checked(python, corpus.root)
    fixes: _Fixing = _fixes(python, corpus, version)
    seconds: float = time.perf_counter() - start
    _ = sys.stderr.write(f"{version} on {corpus.name}: {files} files in {seconds:.1f}s\n")
    return Measured(corpus, label(version, name), files, codes, levels, *fixes)


def _table(rows: Sequence[Sequence[object]], right: int) -> list[str]:
    """Lay a table out as Prettier does, so CI's `prettier --check` passes on what this writes.

    `rows[0]` is the header; the first `right` columns align left, the rest (numbers) right.

    Returns:
      Its lines: the header, the alignment row, then each row, every cell padded to its column.

    """
    cells: list[list[str]] = [[str(cell) for cell in row] for row in rows]
    widths: list[int] = [max(3, *(len(row[i]) for row in cells)) for i in range(len(cells[0]))]
    separator: list[str] = ["-" * w if i < right else "-" * (w - 1) + ":" for i, w in enumerate(widths)]

    def line(row: Sequence[str]) -> str:
        padded: list[str] = [
            cell.ljust(widths[i]) if i < right else cell.rjust(widths[i]) for i, cell in enumerate(row)
        ]
        return "| " + " | ".join(padded) + " |"

    return [line(cells[0]), "| " + " | ".join(separator) + " |", *(line(row) for row in cells[1:])]


def _number(count: int | None) -> str:
    return "crashed" if count is None else f"{count:,}"


def _sum(counts: Iterable[int | None]) -> int | None:
    """Add up a column.

    Returns:
      Its total, or `None` (crashed) if any row's is.

    """
    known: list[int | None] = list(counts)
    return None if None in known else sum(count or 0 for count in known)


def _share(count: int | None, whole: int) -> str:
    """Write `count` with its percentage of `whole`.

    Returns:
      It, as `1,234 (5.6%)`; a crash, or a count of nothing, without one.

    """
    return _number(count) if count is None or not whole else f"{count:,} ({count / whole:.1%})"


def _offences(m: Measured) -> int:
    """Count a row's offences: everything `suffocate`, which reports every code, finds.

    Returns:
      Its errors and warnings there.

    """
    return sum(m.levels[Level.SUFFOCATE])


def _code_rows(rows: Sequence[Measured], codes: Sequence[str]) -> list[list[str]]:
    """Lay out one version's rows of offences per code, then their total.

    Returns:
      A row per corpus (its offences per code, and all of them), then a **Total** row with each
      code's share of every offence.

    """
    found: list[list[str]] = [
        [
            m.corpus.name,
            m.corpus.version,
            m.version,
            _number(m.files),
            *(_number(m.codes[c]) for c in codes),
            _number(m.codes.total()),
        ]
        for m in rows
    ]
    everything: int = sum(m.codes.total() for m in rows)
    total: list[str] = [
        "**Total**",
        "",
        rows[0].version,
        _number(sum(m.files for m in rows)),
        *(_share(sum(m.codes[c] for m in rows), everything) for c in codes),
        _number(everything),
    ]
    return [*found, total]


def _level_rows(rows: Sequence[Measured]) -> list[list[str]]:
    """Lay out one version's rows of errors and warnings per level and `--fix`'s results, then their total.

    Returns:
      A row per corpus, then a **Total** row; what was fixed and guessed is also a share of the
      offences `suffocate` finds.

    """
    levels: list[Level] = list(Level)

    def row(name: str, m: Sequence[Measured]) -> list[str]:
        offences: int = sum(_offences(one) for one in m)
        return [
            name,
            m[0].version,
            *(
                f"{_number(sum(one.levels[level][0] for one in m))} / "
                + _number(sum(one.levels[level][1] for one in m))
                for level in levels
            ),
            _share(_sum(one.fixed for one in m), offences),
            _share(_sum(one.guessed for one in m), offences),
            _number(sum(one.broken for one in m)),
            _number(sum(one.left for one in m)),
        ]

    return [*(row(m.corpus.name, [m]) for m in rows), row("**Total**", rows)]


def tables(measured: Sequence[Measured]) -> str:
    """Write the two tables as Markdown, a row per corpus and a total per version.

    Returns:
      The offences per code at `suffocate` (every code a version reports), then each level's errors
      and warnings and what `--fix` did, with a line naming the Python they came from.

    """
    codes: list[str] = sorted({code for m in measured for code in m.codes})
    versions: list[list[Measured]] = [
        [m for m in measured if m.version == version]
        for version in dict.fromkeys(m.version for m in measured)
    ]
    first: list[str] = _table(
        [
            ["Corpus", "Version", "constricter", "Files", *(f"`{code}`" for code in codes), "Total"],
            *(row for rows in versions for row in _code_rows(rows, codes)),
        ],
        right=3,
    )
    second: list[str] = _table(
        [
            [
                "Corpus",
                "constricter",
                *(f"`{level.name.lower()}`" for level in Level),
                "Fixed",
                "Guessed",
                "Broken",
                "Left",
            ],
            *(row for rows in versions for row in _level_rows(rows)),
        ],
        right=2,
    )
    python: str = sys.version.split()[0]
    # Filled to 100 columns, as Prettier fills a paragraph, so CI's `prettier --check` passes.
    codes_note: str = textwrap.fill(
        " ".join(
            [
                f"Offences per code at `suffocate`, with `all-scopes` (Python {python});",
                "the total row gives each code's share of them:",
            ],
        ),
        width=_PROSE_WIDTH,
    )
    levels_note: str = textwrap.fill(_LEVELS_NOTE, width=_PROSE_WIDTH)
    return "\n".join(
        [
            codes_note,
            "",
            *first,
            "",
            levels_note,
            "",
            *second,
            "",
            textwrap.fill(_GROWTH_NOTE, width=_PROSE_WIDTH),
            "",
            *_table([_GROWTH_HEADER, *(row for rows in versions for row in _growth_rows(rows))], right=2),
        ],
    )


def _grown(before: Size, after: Size | None, fixes: int | None) -> tuple[str, str, str]:
    """Write how much fixing grew a tree: bytes, lines, and bytes per fix.

    Returns:
      The three cells (`crashed` if the fix did).

    """
    if after is None or fixes is None:
        return "crashed", "crashed", "crashed"
    grown: int = after.size - before.size
    return (
        _share(grown, before.size),
        _share(after.lines - before.lines, before.lines),
        f"{grown / fixes:.1f}" if fixes else "-",
    )


def _growth_rows(rows: Sequence[Measured]) -> list[list[str]]:
    """Lay out one version's growth under `--fix`, a row per corpus, then their total.

    Returns:
      The rows: each corpus's size, then what `--fix` and `--fix --unsafe-fixes` added.

    """

    def row(name: str, m: Sequence[Measured]) -> list[str]:
        before: Size = Size(sum(one.size.size for one in m), sum(one.size.lines for one in m))
        fixed: int | None = _sum(one.fixed for one in m)
        both: int | None = None if fixed is None else _sum(one.guessed for one in m)
        after: Size | None = _added(one.fixed_size for one in m)
        unsafe: Size | None = _added(one.unsafe_size for one in m)
        return [
            name,
            m[0].version,
            f"{before.size:,}",
            f"{before.lines:,}",
            *_grown(before, after, fixed),
            *_grown(before, unsafe, None if both is None or fixed is None else fixed + both),
        ]

    return [*(row(m.corpus.name, [m]) for m in rows), row("**Total**", rows)]


def _added(sizes: Iterable[Size | None]) -> Size | None:
    """Add sizes up.

    Returns:
      Their total, or `None` (crashed) if any is.

    """
    known: list[Size | None] = list(sizes)
    return (
        None if None in known else Size(*(sum(part) for part in zip(*cast("list[Size]", known), strict=True)))
    )


def record(measured: Sequence[Measured], runs: Path = RUNS, *, replace: bool = False) -> None:
    """Write a section per version into `runs`, replacing a release's section if it's there.

    Sections stay in the order they were first added: a new version's is appended. `dev` is
    recorded under this checkout's own version (so run it right after bumping the version for a
    release), and never over a section already there unless `replace`: that version was
    released, and its section is the release's.

    Raises:
      ValueError: `dev` would overwrite a recorded version.

    """
    text: str = runs.read_text(encoding="utf-8") if runs.exists() else _RUNS_HEADER
    head: str
    rest: list[str]
    head, *rest = text.split(f"\n{_SECTION}")
    sections: dict[str, str] = {}
    part: str
    for part in rest:
        name: str = part.split("\n", 1)[0]
        sections[name] = part
    version: str
    for version in dict.fromkeys(m.version for m in measured):
        release: str = version.removesuffix(f"+{DEV}")
        if release != version and release in sections and not replace:
            message: str = f"{runs} already has {release}: bump the version first, or pass --replace"
            raise ValueError(message)
        rows: list[Measured] = [m._replace(version=release) for m in measured if m.version == version]
        sections[release] = f"{release}\n\n{tables(rows)}\n"
    body: str = "".join(f"\n{_SECTION}{part.rstrip()}\n" for part in sections.values())
    _ = runs.write_text(f"{head.rstrip()}\n{body}", encoding="utf-8")


def main(argv: Sequence[str]) -> int:
    """Measure every corpus with every version, print the tables and, with `--write`, record them.

    Returns:
      0.

    """
    versions: list[str] = list(VERSIONS)
    if _VERSIONS_FLAG in argv:
        versions = argv[argv.index(_VERSIONS_FLAG) + 1].split(",")
    name: str = argv[argv.index(_LABEL_FLAG) + 1] if _LABEL_FLAG in argv else __version__
    measured: list[Measured] = [
        measure(corpus, version, name) for version in versions for corpus in corpora()
    ]
    _ = sys.stdout.write(f"{tables(measured)}\n")
    if _WRITE_FLAG in argv:
        record(measured, replace=_REPLACE_FLAG in argv)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
